//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopItem
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> QuantityAvailable { get; set; }
    }
}
